server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
   
    path('yorumlar/', views.yorumlar, name='yorumlar'),
    path('figen_hoca_kimdir/', views.figen_hoca_kimdir, name='figen_hoca_kimdir'),
    path('dersler_hakkinda/', views.dersler_hakkinda, name='dersler_hakkinda'),
    path('iletisim/', views.iletisim, name='iletisim'),
 

    path(route='', view=views.get_feedbacks, name='index'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now
from django.core import serializers 
import uuid
import json

class UserFeedback:
    def __init__(self, name, surname, feedback,email,date):
        self.name = name
        self.surname = surname
        self.email = email
        self.feedback = feedback
        self.date=date


    def __str__(self):
        return "Feedback: " + self.feedback

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
# from .models import related models
# from .restapis import related methods
from .models import UserFeedback
from .restapis import get_feedback,post_request
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json
from datetime import date

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.

def yorumlar(request):
     if request.method == "GET":
        url = "https://439290d0.eu-de.apigw.appdomain.cloud/driving/feedbacks"
        feedbacks = get_feedback(url)
        context = {}
        feedbacks.sort(key=lambda x: datetime.strptime(x.date, '%d/%m/%Y'),reverse=True)
        context["feedbacks"] = feedbacks
        return render(request, 'djangoapp/yorumlar.html', context)
     elif request.method == "POST":
        feedback = {}
        form = request.POST
        feedback["name"] = form["name"]
        feedback["surname"] =form["surname"]
        feedback["email"]=form["email"]
        feedback["feedback"] = form["fback"]
        feedback["date"]= date.today().strftime("%d/%m/%Y")
        post_url = "https://439290d0.eu-de.apigw.appdomain.cloud/driving/feedbacks"
        json_payload = { "feedback": feedback }
        post_request(post_url, json_payload)
        return redirect("djangoapp:yorumlar")




def get_feedbacks(request):
    if request.method == "GET":
        url = "https://439290d0.eu-de.apigw.appdomain.cloud/driving/feedbacks"
        feedbacks = get_feedback(url)
        context = {}
        feedbacks.sort(key=lambda x: datetime.strptime(x.date, '%d/%m/%Y'),reverse=True)
        context["feedbacks"] = feedbacks
        return render(request, 'djangoapp/index.html', context)
    elif request.method == "POST":
        feedback = {}
        form = request.POST
        feedback["name"] = form["name"]
        feedback["surname"] =form["surname"]
        feedback["email"]=form["email"]
        feedback["feedback"] = form["fback"]
        feedback["date"]= date.today().strftime("%d/%m/%Y")
        post_url = "https://439290d0.eu-de.apigw.appdomain.cloud/driving/feedbacks"
        json_payload = { "feedback": feedback }
        post_request(post_url, json_payload)
        return redirect("djangoapp:index")


def figen_hoca_kimdir(request):
    context = {}
    return render(request, 'djangoapp/figen_hoca_kimdir.html', context)

def dersler_hakkinda(request):
    context = {}
    return render(request, 'djangoapp/dersler_hakkinda.html', context)

def iletisim(request):
    context = {}
    return render(request, 'djangoapp/iletisim.html', context)
   

server/djangoapp/templates/djangoapp/dersler_hakkinda.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dersler Hakkında</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <style>
      
        * {box-sizing: border-box}
        body {font-family: Verdana, sans-serif; 
        margin:0; font-size: 20px;
        }
        
        ul.second {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
          background-color: #333;
          position: -webkit-sticky; /* Safari */
          position: sticky;
          top: 0;
        }
        
        li.first {
          float: left;
          padding: 10x
        }
        
        li a {
          display: block;
          color: white;
          text-align: center;
          padding: 14px 20px;
          text-decoration: none;
        }
        
        li a:hover {
          background-color: #978AA8;
        }
        .column {
         float: left;
         padding: 40x;
        }

        .left {
         width: 60%;
        }

        .right {
         width: 40%;
        }

        /* Clear floats after the columns */
        .row:after {
         content: "";
         display: table;
         clear: both;
        }
        div.overflow {
        
        width: 47rem; 
        
        }
        
      
        p.ex1 {
        padding-left: 80px;
        padding-right: 80px;
        border-style: outset;
        }
        
        .fa-instagram {   /* instagram icon */
        background: #125688;
        color: white;
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
        }
        .fa-facebook {
        background: #3B5998;
        color: white;
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
        }
        .fa-phone {
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
        }
        img{
        display: block;
        margin-left: auto;
        margin-right: auto;
        }
        .container-fluid{
        max-width: 1000px;
        margin: auto;
        }
        
        </style>
</head>

    <body>
        
          
          <ul class="second">
            <li class="first"><a href="{% url 'djangoapp:index' %}">Anasayfa</a></li>
            <li class="first"><a href="{% url 'djangoapp:figen_hoca_kimdir' %}">Figen Hoca Kimdir?</a></li>
            <li class="first"><a href="{% url 'djangoapp:dersler_hakkinda' %}">Dersler Hakkında</a></li>
            <li class="first"><a href="{% url 'djangoapp:yorumlar' %}">Öğrenci Yorumları</a></li>
            <li class="first"><a href="{% url 'djangoapp:iletisim' %}">İletişim</a></li>
          </ul>
          <div class="container-fluid">
          <a href="https://www.instagram.com/direksiyondersi.figenhoca/" class="fa fa-instagram"></a>    <!-- instagram icon -->
          <a href="https://www.facebook.com/figen.korkutan" class="fa fa-facebook"></a>    <!-- facebook icon -->
          <a href="tel:+905352323149">
            <i class="fa fa-phone" style="font-size:48px;color:red"></i>
          </a> 
        

        <br>
        <br>
        <img src=" https://asilsurucukursu.com.tr/wp-content/uploads/2017/06/banner4.jpg" 
        style="width:80%;" height="400" >
        <br>
        <br>

        <p class="ex1"> <strong> Dersler sizin aracınızda verilir. Bir günde en az iki ders yapılır. 
            Figen Hoca hafta içi sabah dokuzdan akşam sekize kadar ders verir. Dersinizden bi önceki güne 
            kadar iptal etme hakkınız vardır. Fiyat blgisi almak için Figen Hoca ile iletişime geçiniz.
           
        </strong></p1>
    </div>
         
          

    </body>

</html>

server/djangoapp/templates/djangoapp/figen_hoca_kimdir.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Öğrenci Yorumları</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <style>
      
        * {box-sizing: border-box}
        body {font-family: Verdana, sans-serif; 
        margin:0; font-size: 20px;
        }
        
        ul.second {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
          background-color: #333;
          position: -webkit-sticky; /* Safari */
          position: sticky;
          top: 0;
        }
        
        li.first {
          float: left;
          padding: 10x
        }
        
        li a {
          display: block;
          color: white;
          text-align: center;
          padding: 14px 20px;
          text-decoration: none;
        }
        
        li a:hover {
          background-color: #978AA8;
        }
        .column {
         float: left;
         padding: 40x;
        }

        .left {
         width: 60%;
        }

        .right {
         width: 40%;
        }

        /* Clear floats after the columns */
        .row:after {
         content: "";
         display: table;
         clear: both;
        }
        div.overflow {
        
        width: 47rem; 
        
        }
        
        .centered {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        }
        p.ex1 {
        padding-left: 80px;
        padding-right: 80px;
        border-style: outset;
        }
        
        .fa-instagram {   /* instagram icon */
        background: #125688;
        color: white;
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
        }
        .fa-facebook {
        background: #3B5998;
        color: white;
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
        }
        .fa-phone {
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
}
        .container-fluid{
        max-width: 1000px;
        margin: auto;
        }
        
        </style>
</head>

    <body>
        
          
          <ul class="second">
            <li class="first"><a href="{% url 'djangoapp:index' %}">Anasayfa</a></li>
            <li class="first"><a href="{% url 'djangoapp:figen_hoca_kimdir' %}">Figen Hoca Kimdir?</a></li>
            <li class="first"><a href="{% url 'djangoapp:dersler_hakkinda' %}">Dersler Hakkında</a></li>
            <li class="first"><a href="{% url 'djangoapp:yorumlar' %}">Öğrenci Yorumları</a></li>
            <li class="first"><a href="{% url 'djangoapp:iletisim' %}">İletişim</a></li>
          </ul>
          <div class="container-fluid">
          <a href="https://www.instagram.com/direksiyondersi.figenhoca/" class="fa fa-instagram"></a>    <!-- instagram icon -->
          <a href="https://www.facebook.com/figen.korkutan" class="fa fa-facebook"></a>    <!-- facebook icon -->
          <a href="tel:+905352323149">
            <i class="fa fa-phone" style="font-size:48px;color:red"></i>
          </a> 

        <br>
        <br>
        <p class="ex1"> <strong> Figen Korkutan İstanbul'da ikamet etmektedir. Çeşitli sürücü kurslarında direksiyon  
            eğitimi verdikten sonra özel direkyiyon hocası olarak meslek hayatına devam etmektedir. MEB Onaylı direksiyon hocası
            Figen Hoca 25 yıllık meslek tecrübesine sahiptir. Engin bilgisi ve sıcak kanlı yapısıyla ders verdiği öğrencilerinin hepsi en kısa sürede
            trafikte yaşağı korkuları yenmiş ve güçlü bir direksiyon hakimiyeti kazanmıştır.</strong></p1>
          
        </div>
          

    </body>

</html>

server/djangoapp/templates/djangoapp/iletisim.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>İletişim</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <style>
      
        * {box-sizing: border-box}
        body {font-family: Verdana, sans-serif; 
        margin:0; font-size: 20px;
        }
        
        ul.second {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
          background-color: #333;
          position: -webkit-sticky; /* Safari */
          position: sticky;
          top: 0;
        }
        
        li.first {
          float: left;
          padding: 10x
        }
        
        li a {
          display: block;
          color: white;
          text-align: center;
          padding: 14px 20px;
          text-decoration: none;
        }
        
        li a:hover {
          background-color: #978AA8;
        }
        .column {
         float: left;
         padding: 40x;
        }

        .left {
         width: 60%;
        }

        .right {
         width: 40%;
        }

        /* Clear floats after the columns */
        .row:after {
         content: "";
         display: table;
         clear: both;
        }
        div.overflow {
        
        width: 47rem; 
        
        }
        
      
        p.ex1 {
        padding-left: 80px;
        padding-right: 80px;
        border-style: outset;
        }
        
        .fa-instagram {   /* instagram icon */
        background: #125688;
        color: white;
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
        }
        .fa-facebook {
        background: #3B5998;
        color: white;
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
        }
        .fa-phone {
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
        }
        img{
        display: block;
        margin-left: auto;
        margin-right: auto;
        }
        .container-fluid{
        max-width: 1000px;
        margin: auto;
        }
        
        </style>
</head>

    <body>
        
          
          <ul class="second">
            <li class="first"><a href="{% url 'djangoapp:index' %}">Anasayfa</a></li>
            <li class="first"><a href="{% url 'djangoapp:figen_hoca_kimdir' %}">Figen Hoca Kimdir?</a></li>
            <li class="first"><a href="{% url 'djangoapp:dersler_hakkinda' %}">Dersler Hakkında</a></li>
            <li class="first"><a href="{% url 'djangoapp:yorumlar' %}">Öğrenci Yorumları</a></li>
            <li class="first"><a href="{% url 'djangoapp:iletisim' %}">İletişim</a></li>
          </ul>
          <div class="container-fluid">
          <a href="https://www.instagram.com/direksiyondersi.figenhoca/" class="fa fa-instagram"></a>    <!-- instagram icon -->
          <a href="https://www.facebook.com/figen.korkutan" class="fa fa-facebook"></a>    <!-- facebook icon -->
          <a href="tel:+905352323149">
            <i class="fa fa-phone" style="font-size:48px;color:red"></i>
          </a> 

        <br>
        <br>
        <img src="https://cdn.hbrturkiye.com/r/1000x0/var/uploads/content/1551683546-dijital-ortamda-daha-etkin-iletisim-icin-oneriler-jpg.jpg" 
        style="width:80%;" height="400" >
        <br>
        <br>

        <p class="ex1"> <strong> Figen hocayı +905352323149
       numaralı telefonunda arayabilir veya intagram'da dm den iletişime geçebilirsiniz
           
        </strong></p1>
    </div>
          
         
          

    </body>

</html>

server/djangoapp/templates/djangoapp/yorumlar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Öğrenci Yorumları</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <style>
      
        * {box-sizing: border-box}
        body {font-family: Verdana, sans-serif; 
        margin:0; font-size: 20px;
        }
        
        ul.second {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
          background-color: #333;
          position: -webkit-sticky; /* Safari */
          position: sticky;
          top: 0;
        }
        
        li.first {
          float: left;
          padding: 10x
        }
        
        li a {
          display: block;
          color: white;
          text-align: center;
          padding: 14px 20px;
          text-decoration: none;
        }
        
        li a:hover {
          background-color: #978AA8;
        }
        .column {
         float: left;
         padding: 40x;
        }

        .left {
         width: 60%;
        }

        .right {
         width: 40%;
        }

        /* Clear floats after the columns */
        .row:after {
         content: "";
         display: table;
         clear: both;
        }
        div.overflow {
        
        width: 60rem; 
        
        }
        
        .centered {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        }
        p.ex1 {
        padding-left: 80px;
        padding-right: 80px;
        border-style: outset;
        }
        
        .fa-instagram {   /* instagram icon */
        background: #125688;
        color: white;
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
        }
        .fa-facebook {
        background: #3B5998;
        color: white;
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
        }
        .fa-phone {
        padding: 5px;
        font-size: 40px;
        width: 60px;
        text-align: center;
        text-decoration: none;
        margin: 5px 2px;
        position:Relative;
}       
        .container-fluid{
        max-width: 1000px;
        margin: auto;
        }
        
        </style>
</head>

    <body>
        
          
          <ul class="second">
            <li class="first"><a href="{% url 'djangoapp:index' %}">Anasayfa</a></li>
            <li class="first"><a href="{% url 'djangoapp:figen_hoca_kimdir' %}">Figen Hoca Kimdir?</a></li>
            <li class="first"><a href="{% url 'djangoapp:dersler_hakkinda' %}">Dersler Hakkında</a></li>
            <li class="first"><a href="{% url 'djangoapp:yorumlar' %}">Öğrenci Yorumları</a></li>
            <li class="first"><a href="{% url 'djangoapp:iletisim' %}">İletişim</a></li>
          </ul>
          <div class="container-fluid">
          <a href="https://www.instagram.com/direksiyondersi.figenhoca/" class="fa fa-instagram"></a>    <!-- instagram icon -->
          <a href="https://www.facebook.com/figen.korkutan" class="fa fa-facebook"></a>    <!-- facebook icon -->
          <a href="tel:+905352323149">
            <i class="fa fa-phone" style="font-size:48px;color:red"></i>
          </a> 
          </div>

       
        <br>
        <div class="container-fluid">
            <form action="{% url 'djangoapp:index' %}"method="post">
                <h8> Yorum Yaz </h8>
                <div class="form-group">
        
                      <div class="mb-3">
                          <label for="name"><b style="font-size: 0.800em;">İsim: </b></label>
                          <textarea class="form-control" id="name" name="name" rows="1" required></textarea>
                      </div>
        
                      <div class="mb-3">
                        <label for="surname"><b style="font-size: 0.800em;">Soyisim: </b></label>
                        <textarea class="form-control" id="surname" name="surname" rows="1" required></textarea>
                      </div>
        
                      <div class="mb-3">
                        <label for="email"><b style="font-size: 0.800em;">email: </b></label>
                        <textarea class="form-control" id="email" name="email" rows="1" required></textarea>
                      </div>
        
                      <div class="mb-3">
                          <label for="fback"><b style="font-size: 0.800em;">Yorum: </b></label>
                          <textarea class="form-control" id="fback" name="fback" rows="1" required></textarea>
                      </div>
        
                </div>
                {% csrf_token %}
                <div>
                    <button class="btn btn-primary" type="submit">Gönder</button>
                </div>
            </form>
            <br>
            <p class="ex1"> <strong> Figen Hoca'nın Öğrencilerinin Yaptıkları Yorumlar </strong></p1>
        </div>
        <br>
          
         <!-- <div class="row", class="ex1"> -->
         <!--   <div class="column left" style="background-color:#aaa;"> -->
                <div class="container-fluid">
                <div class="card-decks">
                {% for feedback in feedbacks %} 
                        
                        <div class="card border-primary mb-3" style="width: 60rem;">
                            <div class="overflow">
                            <h5 class="card-title">&nbsp;&nbsp;{{feedback.name}}, {{feedback.surname}}
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{feedback.date}} </h5>
                            
                            <p class="card-text" > 
                                <div style="font-size: 0.700em;">&nbsp;&nbsp;{{feedback.feedback}}</div>
                            </p> 
                            
                        </div>    
                </div>
                     
                {% endfor %}
                </div>
               

           <!-- </div> -->
           <!-- </div> -->
           
         
         
          

    </body>

</html>